# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(381, 481)
        Dialog.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setStyleSheet("\n"
"\n"
"QLineEdit:focus {\n"
"    border:2px solid rgb(255, 202, 10);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.username_edit = QtWidgets.QLineEdit(self.frame_3)
        self.username_edit.setGeometry(QtCore.QRect(90, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        self.username_edit.setFont(font)
        self.username_edit.setStyleSheet("")
        self.username_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.username_edit.setObjectName("username_edit")
        self.password_edit = QtWidgets.QLineEdit(self.frame_3)
        self.password_edit.setGeometry(QtCore.QRect(90, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        self.password_edit.setFont(font)
        self.password_edit.setInputMask("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_edit.setObjectName("password_edit")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 250, 191, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.captcha_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.captcha_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.captcha_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(12)
        self.captcha_edit.setFont(font)
        self.captcha_edit.setStyleSheet("QLineEdit {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"")
        self.captcha_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.captcha_edit.setObjectName("captcha_edit")
        self.horizontalLayout_3.addWidget(self.captcha_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.captcha_image_label = QtWidgets.QLabel(self.layoutWidget)
        self.captcha_image_label.setMinimumSize(QtCore.QSize(70, 0))
        self.captcha_image_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.captcha_image_label.setObjectName("captcha_image_label")
        self.horizontalLayout_3.addWidget(self.captcha_image_label)
        self.login_button = QtWidgets.QPushButton(self.frame_3)
        self.login_button.setGeometry(QtCore.QRect(90, 300, 191, 31))
        self.login_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(107, 149, 200);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    \n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.username_edit.setPlaceholderText(_translate("Dialog", "账户"))
        self.password_edit.setPlaceholderText(_translate("Dialog", "密码"))
        self.captcha_edit.setPlaceholderText(_translate("Dialog", "验证码"))
        self.captcha_image_label.setText(_translate("Dialog", "TextLabel"))
        self.login_button.setText(_translate("Dialog", "登录"))
import images_rc
