# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_server_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 441)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.all_frame = QtWidgets.QFrame(Dialog)
        self.all_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.all_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.all_frame.setObjectName("all_frame")
        self.horizontalLayout.addWidget(self.all_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
